# Generated by Django 5.1.2 on 2024-10-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='forums_comm_post_id_b29c27_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='forums_comm_parent__61efa9_idx',
        ),
    ]
