# Generated by Django 5.1.2 on 2024-10-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_comment_forums_comm_post_id_b29c27_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
