# Generated by Django 5.1.2 on 2024-10-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='device',
            name='accounts_de_device__d33a40_idx',
        ),
    ]
